<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<!-- HttpContext ve IHttpContextAccessor için doğru framework referansı -->
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="MassTransit.RabbitMQ" Version="9.2.0" />
	  <PackageReference Include="StackExchange.Redis" Version="3.1.13" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MdgInvoiceManager.Core\MdgInvoiceManager.Core.csproj" />
		<ProjectReference Include="..\MdgInvoiceManager.DataAccess\MdgInvoiceManager.DataAccess.csproj" />
	</ItemGroup>

</Project>